plugins:
  - jekyll-seo-tag

url: "http://dfantuzzi.info"
baseurl: ""

author:
  name: Davide Fantuzzi
  twitter: utnaf
  picture: /img/avatar.jpg

# seo
title: "Davide Fantuzzi"
tagline: "Web tips for developers"
description: "Davide Fantuzzi, Remote Data Engineer @LarusBA. In my blog I'll share some thoughts about software, music, and travels."

role: "Data Engineer"
