plugins:
  - jekyll-paginate

url: "http://dfantuzzi.info"
baseurl: ""
title: "Davide Fantuzzi"
description: "Davide Fantuzzi, Remote Data Engineer @LarusBA. Writing on the web, for the web."
role: "Data Engineer"

paginate: 5
paginate_path: "/blog/page:num/"
